### ISSUE TITLE
destination path

### ISSUE THREAD

**Issue by Lukasss93** [Benau/tgsconverter#1]
Hi! Great package!
Can you implement the ability to save the output file in another path?

Example:
`./tgsconverter sticker.tgs ../converted/yeee.gif`

**Comment by Benau** [comment]
i don't have much time on hacking this project more at the moment....

**Comment by Lukasss93** [comment]
Never mind, I needed asap, so I made a [clone](https://github.com/Lukasss93/tgsconverter).
